
server:
  port: 8080
  servlet:
    context-path: "/"

spring:
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"

springdoc:
  swagger-ui:
    path: "/api.html"

amazon:
  aws:
    accesskey: "fakeAccessKey"
    secretkey: "fakeSecretAccessKey"
  dynamodb:
    endpoint: "http://localhost:8000/"
